### ISSUE TITLE
Ignore patrons in the Campus Person Feed with Empty Expiration dates

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#352] opened 2022-06-02 19:27 UTC
Compare these two files:
alma_people_2022-05-23_2022-05-24_E.xml
alma_people_2022-05-26_2022-05-27_E.xml

The file from May 23rd has patron expiration dates. The file from May 26th does not. This is making all updated users have no expiry date.

This is urgent, especially at the end of the year, when patrons are renewing items. If a patron has no expiration date but they are graduating or leaving the university prior to the due date of materials, they will get due dates that are past when they will be at the university. This also affects the NCIP renewal job, as patrons with no expiration dates do not have their requests passed to the Analytics report that powers the SCSB renewal.

**Comment by carolyncole** [comment] 2022-06-02 20:09
I went ahead and ran the person feed from the production server `` 

```
ssh deploy@lib-jobs-prod1
cd /opt/lib-jobs/current
bundle exec rails c
  people = AlmaPeople::OitPersonFeed.new
  json = people..get_json(begin_date: (Time.zone.now - 1.day).strftime("%Y-%m-%d"), end_date: 
  Time.zone.now.strftime("%Y-%m-%d"))
  json.map{|patron| [patron["PATRON_EXPIRATION_DATE"],patron["PVPATRONGROUP"]]}
```
You can see the expiration is nil for any patron group.

**Comment by kevinreiss** [comment] 2022-09-15 16:43
@mzelesky is this still an issue? Or was this an issue that was on the data side from OIT. Close if there is nothing actionable.

**Comment by mzelesky** [comment] 2022-09-15 16:49
I don't know if it's still an issue. Is there code in place that changes a patron's expiration date if it is set to nil?

**Comment by maxkadel** [comment] 2023-02-13 16:20
I believe this is already in place - confirm, and if so, can close this issue.

**Comment by kevinreiss** [comment] 2023-04-24 18:19
@mzelesky is this something we should put on a radar to check in on before the semester wraps and everyone's dates are reset.

**Comment by kevinreiss** [comment] 2023-04-26 16:47
If expiration date in a patron's record is nil just ignore the update. First check to see if the code already does this. If not then we need to implement it.

**Comment by kevinreiss** [comment] 2023-04-27 13:06
To close out this ticket we need to confirm if our code ignores updates patrons who appear in the Person feed with empty or nil expiration dates.

**Comment by maxkadel** [comment] 2023-04-27 15:16
* https://github.com/pulibrary/lib_jobs/pull/367
* https://github.com/pulibrary/lib_jobs/pull/330

**Comment by sandbergja** [comment] 2023-04-28 21:11
closing as duplicate of #355, which is already fixed.

**Closed by sandbergja** 2023-04-28 21:11 UTC
Labels: investigate
